{"name": "test_add_product_to_cart_with_empty_body", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается статус 422 Unprocessable Entity, но получен статус 401\nassert 401 == 422", "trace": "@allure.feature(\"Тестирование API интернет-магазина\")\n    @allure.story(\"Добавление продукта в корзину с пустым телом\")\n    def test_add_product_to_cart_with_empty_body():\n        \"\"\"\n        Тест для добавления продукта в корзину с пустым телом запроса.\n    \n        Проверяет, как API реагирует на пустой запрос, ожидая, что сервер вернет статус ошибки.\n        \"\"\"\n        with allure.step(\"Отправить пустой запрос в корзину\"):\n            # Создаем объект для отправки запросов к API\n            empt = EmptyPostRequest(API1_url)  # Замените на ваш URL\n            # Вызов метода с пустым телом\n            status_code = empt.add_product_to_cart_with_empty_body()\n    \n        with allure.step(\"Проверить статус запроса\"):\n            # Проверяем, что сервер возвращает статус 422\n>           assert status_code == 422, \"Ожидается статус 422 Unprocessable Entity, но получен статус {}\".format(\n                status_code)\nE           AssertionError: Ожидается статус 422 Unprocessable Entity, но получен статус 401\nE           assert 401 == 422\n\ntest\\test_api.py:139: AssertionError"}, "description": "\nТест для добавления продукта в корзину с пустым телом запроса.\n\nПроверяет, как API реагирует на пустой запрос, ожидая, что сервер вернет статус ошибки.\n", "steps": [{"name": "Отправить пустой запрос в корзину", "status": "passed", "start": 1760898321232, "stop": 1760898321637}, {"name": "Проверить статус запроса", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается статус 422 Unprocessable Entity, но получен статус 401\nassert 401 == 422\n", "trace": "  File \"C:\\Users\\p_kir\\Desktop\\repozit git automatization\\avtomatization\\Chitai-gorod\\test\\test_api.py\", line 139, in test_add_product_to_cart_with_empty_body\n    assert status_code == 422, \"Ожидается статус 422 Unprocessable Entity, но получен статус {}\".format(\n        status_code)\n"}, "start": 1760898321637, "stop": 1760898321637}], "start": 1760898321231, "stop": 1760898321638, "uuid": "18e45f42-6515-4010-818e-f6deae6245de", "historyId": "677be8c2acb07821bd67020d05af5bf6", "testCaseId": "677be8c2acb07821bd67020d05af5bf6", "fullName": "test.test_api#test_add_product_to_cart_with_empty_body", "labels": [{"name": "story", "value": "Добавление продукта в корзину с пустым телом"}, {"name": "feature", "value": "Тестирование API интернет-магазина"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-CE5CAQM"}, {"name": "thread", "value": "24064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api"}], "titlePath": ["test", "test_api.py"]}